### PR TITLE
Docker improvements & memory leak fix

### PR DESCRIPTION
**Pull request by frafra**
I fixed and improved the Docker setup. I also changed some paths, to keep logs and data separate from the code.

### CODE REVIEW

**Comment by frafra** [comment]
Some tips:
- `del object` does not mean that the garbage collector is going to free the memory, nor that `__del__` will be executed; use a context instead and/or implement a `close`/`terminate` function.
- Avoid using `threading` directly: use `multiprocessing` if possible (it also supports threads)
- Do not catch generic errors, and if you really need to do that, print the stacktrace (this is yet to be fixed)

The progress bar does not work when there are very few steps, but the software is now working, with no memory leaks or hangups.

Feel free to improve this PR.

**Comment by frafra** [comment]
I updated our performance page: https://github.com/NINAnor/bachelor-oppgave-nina/wiki/Performance/_compare/f340bf706590b62a2f03ed08b30d88f314b2088e...efa489f0340e18ab9237eed64412e6cbb9bd0783
Since the number of threads is automatically based on the number of logical cores, I get twice the number of FPS on VDI.

Some type annotations are missing.
It could also be worth to check when this snippet should be executed (after each run, like in this PR, or when the model is unloaded, like the original code tried to do):
```
       torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()
```

@beuss-git would you like to have a look at this PR?

**Comment by beuss-git** [comment]
Thank you for the tips and changes!
This is a lot cleaner than my previous frame grabber solution, but there are a couple of issues.

I think we need to find a better/faster way to load and batch the images. It spends most of the "detection time" just loading and preprocessing the videos into image batches now before starting inference.
The fps gain is great, but we only gain a second or two in total processing time (which is still good though).

Another issue is that there is currently no limit to how many images we load into memory which was done via `max_batches_to_queue` before. This solution wont work with full length video files as it will just balloon the memory until run out of it when decoding the video frames into images.

Do you have any ideas on how we could improve this?

**Comment by frafra** [comment]
Do you mean that the `load` function is the bottleneck? If that is the case, we can process multiple videos in parallel. Otherwise, we would need to avoid calling `read` sequentially to get each frame. For example, we could use a different mechanism to load the frames, without using `cv2` and maybe find a better substitute. 

Instead of changing `max_batches_to_queue` you can act on `chunksize` parameter of the `map_async` function, which I have not specified. If you have 4 threads and a chunk size of 250, you would preload a maximum of 1000 elements. A larger chunk size requires more memory, but could give some performance results. Otherwise, the code uses yield mostly, so the last two queues are not needed anymore, as one thread consumes the results one by one.

**Comment by beuss-git** [comment]
Thanks, I will have a look at the torchvision link.
And yeah, the bottleneck is simply reading the frames from the video.
I tried using the `get_batch` function in decord as well, but I got the same or even worse performance from that.
I also tried camgear and imutil, but the current solution was still the fastest (at least without cuda support, but that depends on the video encoding).

I will tinker a bit with the chunksize :)

**Pull request merged**
